url: "https://gazzilabs.github.io"
baseurl: ""

# Site settings
encoding: "UTF-8"
locale: "en-US"
title: "GazziLabs"
email: "ytcho@gazzi.ai"
description: "Welcome to GazziLabs!"


# Team names, titles and social links
people:
- name: Kiok Ahn, Ph.D.
  pic: 1
  position: CEO, Founder
  desc: Machine Learning & Image Processing Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Youngtak Cho, Ph.D.
  pic: 2
  position: CTO, Lead AI Application
  desc: AI & Image Processing, Visual Programming, Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Mingi Kim, M.S.
  pic: 3
  position: Lead Video Archive Solutions
  desc: AI & Image Processing, Massive digital media archives, DevOps
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Taewon Lee, M.S.
  pic: 4
  position: Lead Media Technology
  desc: Contents Analysis, Distributed Media Processing, Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: It's you
  pic: recruit
  position: We are hiring!
  desc: Come with us!
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: google-plus
  #    url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 7F Start-up Campus,
  - line: 20 Pangyo-ro 289 beon-gil, Bundang-gu,
  - line: Seongnam-si, Gyeonggi-do, 13488, Korea

# Build settings
markdown: kramdown
permalink: pretty
